name: remote_rift_foundation
description: "A set of shared packages containing common UI, utilities, and core logic used across Remote Rift projects."
version: 0.7.0
publish_to: "none"

environment:
  sdk: ^3.10.0

dev_dependencies:
  flutter_lints: ^6.0.0

  remote_rift_tools:
    git:
      url: https://github.com/tomwyr/remote-rift-foundation.git
      ref: 0.7.0
      path: packages/tools
