name: remote_rift_foundation
description: "A set of shared packages containing common UI, utilities, and core logic used across Remote Rift projects."
version: 0.5.1
publish_to: "none"

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0
