name: remote_rift_utils
publish_to: none
version: 0.8.1

environment:
  sdk: ^3.10.0

dependencies:
  json_annotation: ^4.10.0

dev_dependencies:
  test: ^1.25.6
  fake_async: ^1.3.3
  json_serializable: ^6.12.0
  build_runner: ^2.10.5
